### ISSUE TITLE
Abigail Spring Sun - Mermaid Pendant Portrait bug

### ISSUE THREAD

**Issue by Nikslg** [paradigmnomad/SVO#10]
Spring started, and console is overflown with this bug
`[Content Patcher] Can't apply image patch "Seasonal Villager Outfits for ContentPatcher > Harvey Spring Sun - Mermaid Pendant" to Portraits\Harvey: the FromFile file 'Portraits\MermaidPendantOverlay\Abigail\Harvey_spring_Sun_NoVest.png' doesn't exist.`

For some reasons it searches for Harvey's portrait in Abigail's folder...

Edit: Just in case I am married to Abigail, not to Harvey.

**Comment by paradigmnomad** [comment]
This should be resolved in 2.1.11 assuming I found the correct issue.
