### ISSUE TITLE
[Suggestion] Fix bow-leg

### ISSUE THREAD

**Issue by KrisCris** [paradigmnomad/SVO#12]
Hi,
I really love you and your team's work making this game more awesome!

You know, some characters in this game have bowlegs... Abigail, Leah, Maru, and Emily. This looks weird even with the vanilla design.

**Comment by paradigmnomad** [comment]
I don't plan on making a non-bowleg version but you might be interested in [Poltergeister's Seasonal Outfits - Slightly Cuter Aesthetic](https://www.nexusmods.com/stardewvalley/mods/5450) that removes the bowlegs.

**Comment by KrisCris** [comment]
alright. thanks for letting me know
