### ISSUE TITLE
Compatiblity with The Robin Romance Mod

### ISSUE THREAD

**Issue by rikai** [paradigmnomad/SVO#3]
I would very much like to see compatibility with [The Robin Romance Mod](https://www.nexusmods.com/stardewvalley/mods/3239) added at some point.

Robin in this mod is replaced with another NPC named Veronica. Robin herself still exists as a custom NPC labeled internally as "Ram".Veronica is referenced internally as Robin, and as such, the mods conflict and neither gets loaded. The mods otherwise work together.

**Comment by paradigmnomad** [comment]
I will likely not be making a compatibility patch for that mod. However I encourage if someone else wants to make one to please do.
