### ISSUE TITLE
Festival outfit not working

### ISSUE THREAD

**Issue by EgaAP** [paradigmnomad/SVO#7]
Is this a problem or you have to toggle something to make festival outfit working ? Please answer :)

**Comment by paradigmnomad** [comment]
If it's during the Egg Hunt, Luau Soup Drinking, or Moonlight Jellies swimming (those are the 3 that come to mind) it is a known issue. This is because of how the events are handled in the game itself. It has been a known issue for awhile that I can do nothing about.
