### ISSUE TITLE
Minor issue -- Missing sprites for Abigail.

### ISSUE THREAD

**Issue by K4rakara** [paradigmnomad/SVO#9]
Heya! Love this mod. 
During Sams concert (8 heart event), Abigail is missing custom sprites for drumming. She starts and stops the concert with the custom sprites, but during the concert has the default ones. Its not a big issue, its just a little off when she swaps back to the custom sprites mid cut scene.

Looking at the files, it looks like these sprites are the ones that would need to be edited.
![image](https://user-images.githubusercontent.com/40474474/79085526-ee544f80-7d06-11ea-8d02-fdfc9ae9b23f.png)

I wouldn't mind making the edits, if you don't have the time atm. If that's the case, just let me know, and I can make a fork, and then PR when I'm done.

**Comment by K4rakara** [comment]
Worth noting -- upon further inspection, this is only an issue for:
- abigail_fall_indoor_rain
- abigail_fall_indoor_sun
- abigail_fall_outdoor_rain
- abigail_maternity
- abigail_summer_indoor_rain_HatPins
- abigail_summer_indoor_rain_Hoodie
- abigail_summer_indoor_rain_NoHatNoPins
- abigail_summer_indoor_rain_NoHatPins
- abigail_summer_indoor_sun
- abigail_summer_outdoor_rain_hoodie
- abigail_summer_outdoor_nohatnopins
- abigail_summer_outdoor_nohatpins

**Comment by paradigmnomad** [comment]
Thanks! This will be fixed in a coming update :)
